// frontend/src/components/MovieSlider.jsx
import { useEffect, useRef, useState } from "react";
import { useContentStore } from "../store/content";
import axiosInstance from "/frontend/axiosConfig";
import { Link } from "react-router-dom";
import { SMALL_IMG_BASE_URL } from "../utils/constants";
import { ChevronLeft, ChevronRight } from "lucide-react";

const MovieSlider = ({ category }) => {
	const { contentType } = useContentStore();
	const [content, setContent] = useState([]);
	const [showArrows, setShowArrows] = useState(false);

	const sliderRef = useRef(null);

	const formattedCategoryName =
		category.replaceAll("_", " ")[0].toUpperCase() + category.replaceAll("_", " ").slice(1);
	const formattedContentType = contentType === "movie" ? "Movies" : "TV Shows";

	useEffect(() => {
		const getContent = async () => {
			const res = await axiosInstance.get(`/api/v1/${contentType}/${category}`);
			setContent(res.data.content);
		};

		getContent();
	}, [contentType, category]);

	const scrollLeft = () => {
		if (sliderRef.current) {
			sliderRef.current.scrollBy({ left: -sliderRef.current.offsetWidth, behavior: "smooth" });
		}
	};
	const scrollRight = () => {
		sliderRef.current.scrollBy({ left: sliderRef.current.offsetWidth, behavior: "smooth" });
	};

	return (
		<div
			className='bg-black text-white relative px-5 md:px-20'
			onMouseEnter={() => setShowArrows(true)}
			onMouseLeave={() => setShowArrows(false)}
		>
			<h2 className='mb-4 text-2xl font-bold'>
				{formattedCategoryName} {formattedContentType}
			</h2>

			<div className='flex space-x-4 overflow-x-scroll scrollbar-hide' ref={sliderRef}>
				{content.map((item) => (
					<Link to={`/watch/${item.id}`} className='min-w-[250px] relative group' key={item.id}>
						<div className='rounded-lg overflow-hidden'>
							<img
								src={SMALL_IMG_BASE_URL + item.backdrop_path}
								alt='Movie image'
								className='transition-transform duration-300 ease-in-out group-hover:scale-125'
							/>
						</div>
						<p className='mt-2 text-center'>{item.title || item.name}</p>
					</Link>
				))}
			</div>

			{showArrows && (
				<>
					<button
						className='absolute top-1/2 -translate-y-1/2 left-5 md:left-24 flex items-center justify-center
            size-12 rounded-full bg-black bg-opacity-50 hover:bg-opacity-75 text-white z-10
            '
						onClick={scrollLeft}
					>
						<ChevronLeft size={24} />
					</button>

					<button
						className='absolute top-1/2 -translate-y-1/2 right-5 md:right-24 flex items-center justify-center
            size-12 rounded-full bg-black bg-opacity-50 hover:bg-opacity-75 text-white z-10
            '
						onClick={scrollRight}
					>
						<ChevronRight size={24} />
					</button>
				</>
			)}
		</div>
	);
};
export default MovieSlider;

// frontend/src/app/components/movie-slider/movie-slider.component.ts
import { Component, ElementRef, Input, ViewChild, inject, signal, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { ContentService } from '../../services/content.service';
import { LucideAngularModule, ChevronLeft, ChevronRight } from 'lucide-angular';
import { SMALL_IMG_BASE_URL } from '../../constants';

@Component({
    selector: 'app-movie-slider',
    standalone: true,
    imports: [CommonModule, RouterLink, LucideAngularModule], // Using LucideAngularModule directly or with .pick in app config if optimized
    templateUrl: './movie-slider.component.html'
})
export class MovieSliderComponent {
    @Input() category!: string;
    @ViewChild('sliderRef') sliderRef!: ElementRef<HTMLDivElement>;

    contentService = inject(ContentService);
    http = inject(HttpClient);

    content = signal<any[]>([]);
    showArrows = signal(false);

    SMALL_IMG_BASE_URL = SMALL_IMG_BASE_URL;

    constructor() {
        effect(() => {
            const contentType = this.contentService.contentType();
            if (this.category) {
                this.getContent(contentType, this.category);
            }
        });
    }

    getContent(contentType: string, category: string) {
        this.http.get<{ content: any[] }>(`/api/v1/${contentType}/${category}`)
            .subscribe(res => {
                this.content.set(res.content);
            });
    }

    get formattedCategoryName() {
        return this.category.replaceAll("_", " ")[0].toUpperCase() + this.category.replaceAll("_", " ").slice(1);
    }

    get formattedContentType() {
        return this.contentService.contentType() === "movie" ? "Movies" : "TV Shows";
    }

    scrollLeft() {
        if (this.sliderRef && this.sliderRef.nativeElement) {
            this.sliderRef.nativeElement.scrollBy({ left: -this.sliderRef.nativeElement.offsetWidth, behavior: "smooth" });
        }
    }

    scrollRight() {
        if (this.sliderRef && this.sliderRef.nativeElement) {
            this.sliderRef.nativeElement.scrollBy({ left: this.sliderRef.nativeElement.offsetWidth, behavior: "smooth" });
        }
    }
}

<div class="bg-black text-white relative px-5 md:px-20" (mouseenter)="showArrows.set(true)"
    (mouseleave)="showArrows.set(false)">

    <h2 class="mb-4 text-2xl font-bold">
        {{ formattedCategoryName }} {{ formattedContentType }}
    </h2>

    <div class="flex space-x-4 overflow-x-scroll scrollbar-hide" #sliderRef>
        @for (item of content(); track item.id) {
        <a [routerLink]="['/watch', item.id]" class="min-w-[250px] relative group">
            <div class="rounded-lg overflow-hidden">
                <img [src]="SMALL_IMG_BASE_URL + item.backdrop_path" alt="Movie image"
                    class="transition-transform duration-300 ease-in-out group-hover:scale-125" />
            </div>
            <p class="mt-2 text-center">{{ item.title || item.name }}</p>
        </a>
        }
    </div>

    @if (showArrows()) {
    <button
        class="absolute top-1/2 -translate-y-1/2 left-5 md:left-24 flex items-center justify-center size-12 rounded-full bg-black bg-opacity-50 hover:bg-opacity-75 text-white z-10"
        (click)="scrollLeft()">
        <!-- Check lucide-angular usage. If .pick imported, use name="chevron-left" -->
        <lucide-icon name="chevron-left" [size]="24"></lucide-icon>
    </button>

    <button
        class="absolute top-1/2 -translate-y-1/2 right-5 md:right-24 flex items-center justify-center size-12 rounded-full bg-black bg-opacity-50 hover:bg-opacity-75 text-white z-10"
        (click)="scrollRight()">
        <lucide-icon name="chevron-right" [size]="24"></lucide-icon>
    </button>
    }
</div>
