// frontend/src/app/pages/watch-page/watch-page.component.ts
import { Component, ElementRef, OnInit, ViewChild, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { DomSanitizer, SafeResourceUrl } from '@angular/platform-browser';
import { NavbarComponent } from '../../components/navbar/navbar.component';
import { ContentService } from '../../services/content.service';
import { LucideAngularModule, ChevronLeft, ChevronRight } from 'lucide-angular';
import { ORIGINAL_IMG_BASE_URL, SMALL_IMG_BASE_URL } from '../../constants';
// No need for dateFunction, use DatePipe

@Component({
    selector: 'app-watch-page',
    standalone: true,
    imports: [CommonModule, RouterLink, NavbarComponent, LucideAngularModule], // DatePipe is in CommonModule
    templateUrl: './watch-page.component.html'
})
export class WatchPageComponent implements OnInit {
    private route = inject(ActivatedRoute);
    private http = inject(HttpClient);
    public contentService = inject(ContentService);
    private sanitizer = inject(DomSanitizer);

    @ViewChild('sliderRef') sliderRef!: ElementRef<HTMLDivElement>;

    id = signal<string | null>(null);
    trailers = signal<any[]>([]);
    currentTrailerIdx = signal(0);
    loading = signal(true);
    content = signal<any>(null);
    similarContent = signal<any[]>([]);

    ORIGINAL_IMG_BASE_URL = ORIGINAL_IMG_BASE_URL;
    SMALL_IMG_BASE_URL = SMALL_IMG_BASE_URL;

    ngOnInit() {
        this.route.paramMap.subscribe(params => {
            const id = params.get('id');
            this.id.set(id);
            if (id) {
                this.loadData(id);
            }
        });

        // Handle contentType changes? 
        // Usually navigating to watch page implies a content type or it's part of the route. 
        // In the React app, it uses store's contentType.
        // If user navigates from movie to tv show, ID changes, but contentType might need to update? 
        // The previous implementation relied on the store's state which was set by Navbar/Home.
        // We assume store is correct.
    }

    loadData(id: string) {
        const type = this.contentService.contentType();
        this.loading.set(true);

        // Trailers
        this.http.get<{ trailers: any[] }>(`/api/v1/${type}/${id}/trailers`)
            .subscribe({
                next: (res) => this.trailers.set(res.trailers),
                error: () => this.trailers.set([])
            });

        // Similar
        this.http.get<{ similar: any[] }>(`/api/v1/${type}/${id}/similar`)
            .subscribe({
                next: (res) => this.similarContent.set(res.similar),
                error: () => this.similarContent.set([])
            });

        // Details
        this.http.get<{ content: any }>(`/api/v1/${type}/${id}/details`)
            .subscribe({
                next: (res) => {
                    this.content.set(res.content);
                    this.loading.set(false);
                },
                error: () => {
                    this.content.set(null);
                    this.loading.set(false);
                }
            });
    }

    getSafeUrl(key: string): SafeResourceUrl {
        return this.sanitizer.bypassSecurityTrustResourceUrl(`https://www.youtube.com/embed/${key}?autoplay=0`); // ReactPlayer logic might differ slightly, using embed
    }

    handleNext() {
        if (this.currentTrailerIdx() < this.trailers().length - 1) {
            this.currentTrailerIdx.update(v => v + 1);
        }
    }

    handlePrev() {
        if (this.currentTrailerIdx() > 0) {
            this.currentTrailerIdx.update(v => v - 1);
        }
    }

    scrollLeft() {
        if (this.sliderRef?.nativeElement) {
            this.sliderRef.nativeElement.scrollBy({ left: -this.sliderRef.nativeElement.offsetWidth, behavior: "smooth" });
        }
    }

    scrollRight() {
        if (this.sliderRef?.nativeElement) {
            this.sliderRef.nativeElement.scrollBy({ left: this.sliderRef.nativeElement.offsetWidth, behavior: "smooth" });
        }
    }
}

<div class="bg-black min-h-screen text-white">
    <div class="mx-auto container px-4 py-8 h-full">
        <app-navbar></app-navbar>

        @if (loading()) {
        <div class="min-h-screen bg-black p-10 flex justify-center items-center">
            <!-- Skeleton or simple loader -->
            <div class="animate-spin rounded-full h-32 w-32 border-t-2 border-b-2 border-red-500"></div>
        </div>
        } @else if (!content()) {
        <div class="bg-black text-white h-screen">
            <div class="max-w-6xl mx-auto">
                <div class="text-center mx-auto px-4 py-8 h-full mt-40">
                    <h2 class="text-2xl sm:text-5xl font-bold text-balance">Content not found 😥</h2>
                </div>
            </div>
        </div>
        } @else {
        <!-- Trailers Navigation -->
        @if (trailers().length > 0) {
        <div class="flex justify-between items-center mb-4">
            <button class="bg-gray-500/70 hover:bg-gray-500 text-white py-2 px-4 rounded"
                [class.opacity-50]="currentTrailerIdx() === 0" [class.cursor-not-allowed]="currentTrailerIdx() === 0"
                [disabled]="currentTrailerIdx() === 0" (click)="handlePrev()">
                <lucide-icon name="chevron-left" [size]="24"></lucide-icon>
            </button>

            <button class="bg-gray-500/70 hover:bg-gray-500 text-white py-2 px-4 rounded"
                [class.opacity-50]="currentTrailerIdx() === trailers().length - 1"
                [class.cursor-not-allowed]="currentTrailerIdx() === trailers().length - 1"
                [disabled]="currentTrailerIdx() === trailers().length - 1" (click)="handleNext()">
                <lucide-icon name="chevron-right" [size]="24"></lucide-icon>
            </button>
        </div>
        }

        <!-- Video Player -->
        <div class="aspect-video mb-8 p-2 sm:px-10 md:px-32">
            @if (trailers().length > 0) {
            <iframe [src]="getSafeUrl(trailers()[currentTrailerIdx()].key)"
                class="w-full h-full rounded-lg overflow-hidden" frameborder="0" allowfullscreen
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture">
            </iframe>
            } @else {
            <h2 class="text-xl text-center mt-5">
                No trailers available for
                <span class="font-bold text-red-600">{{ content()?.title || content()?.name }}</span> 😥
            </h2>
            }
        </div>

        <!-- Details -->
        <div class="flex flex-col md:flex-row items-center justify-between gap-20 max-w-6xl mx-auto">
            <div class="mb-4 md:mb-0">
                <h2 class="text-5xl font-bold text-balance">{{ content()?.title || content()?.name }}</h2>

                <p class="mt-2 text-lg">
                    {{ (content()?.release_date || content()?.first_air_date) | date:'longDate' }}
                    |
                    @if (content()?.adult) {
                    <span class="text-red-600">18+</span>
                    } @else {
                    <span class="text-green-600">PG-13</span>
                    }
                </p>
                <p class="mt-4 text-lg">{{ content()?.overview }}</p>
            </div>
            <img [src]="ORIGINAL_IMG_BASE_URL + content()?.poster_path" alt="Poster image"
                class="max-h-[600px] rounded-md" />
        </div>

        <!-- Similar Content -->
        @if (similarContent().length > 0) {
        <div class="mt-12 max-w-5xl mx-auto relative">
            <h3 class="text-3xl font-bold mb-4">Similar Movies/Tv Show</h3>

            <div class="flex overflow-x-scroll scrollbar-hide gap-4 pb-4 group" #sliderRef>
                @for (item of similarContent(); track item.id) {
                @if (item.poster_path) {
                <a [routerLink]="['/watch', item.id]" class="w-52 flex-none">
                    <img [src]="SMALL_IMG_BASE_URL + item.poster_path" alt="Poster path"
                        class="w-full h-auto rounded-md" />
                    <h4 class="mt-2 text-lg font-semibold">{{ item.title || item.name }}</h4>
                </a>
                }
                }
            </div>

            <lucide-icon name="chevron-right"
                class="absolute top-1/2 -translate-y-1/2 right-2 w-8 h-8 opacity-0 group-hover:opacity-100 transition-all duration-300 cursor-pointer bg-red-600 text-white rounded-full"
                (click)="scrollRight()">
            </lucide-icon>

            <lucide-icon name="chevron-left"
                class="absolute top-1/2 -translate-y-1/2 left-2 w-8 h-8 opacity-0 group-hover:opacity-100 transition-all duration-300 cursor-pointer bg-red-600 text-white rounded-full"
                (click)="scrollLeft()">
            </lucide-icon>
        </div>
        }
        }
    </div>
</div>

// frontend/src/pages/WatchPage.jsx
import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useContentStore } from "../store/content";
import axiosInstance from "/frontend/axiosConfig";
import Navbar from "../components/Navbar";
import { ChevronLeft, ChevronRight } from "lucide-react";
import ReactPlayer from "react-player";
import { ORIGINAL_IMG_BASE_URL, SMALL_IMG_BASE_URL } from "../utils/constants";
import { formatReleaseDate } from "../utils/dateFunction";
import WatchPageSkeleton from "../components/skeletons/WatchPageSkeleton";

const WatchPage = () => {
	const { id } = useParams();
	const [trailers, setTrailers] = useState([]);
	const [currentTrailerIdx, setCurrentTrailerIdx] = useState(0);
	const [loading, setLoading] = useState(true);
	const [content, setContent] = useState({});
	const [similarContent, setSimilarContent] = useState([]);
	const { contentType } = useContentStore();

	const sliderRef = useRef(null);

	useEffect(() => {
		const getTrailers = async () => {
			try {
				const res = await axiosInstance.get(`/api/v1/${contentType}/${id}/trailers`);
				setTrailers(res.data.trailers);
			} catch (error) {
				if (error.message.includes("404")) {
					setTrailers([]);
				}
			}
		};

		getTrailers();
	}, [contentType, id]);

	useEffect(() => {
		const getSimilarContent = async () => {
			try {
				const res = await axiosInstance.get(`/api/v1/${contentType}/${id}/similar`);
				setSimilarContent(res.data.similar);
			} catch (error) {
				if (error.message.includes("404")) {
					setSimilarContent([]);
				}
			}
		};

		getSimilarContent();
	}, [contentType, id]);

	useEffect(() => {
		const getContentDetails = async () => {
			try {
				const res = await axiosInstance.get(`/api/v1/${contentType}/${id}/details`);
				setContent(res.data.content);
			} catch (error) {
				if (error.message.includes("404")) {
					setContent(null);
				}
			} finally {
				setLoading(false);
			}
		};

		getContentDetails();
	}, [contentType, id]);

	const handleNext = () => {
		if (currentTrailerIdx < trailers.length - 1) setCurrentTrailerIdx(currentTrailerIdx + 1);
	};
	const handlePrev = () => {
		if (currentTrailerIdx > 0) setCurrentTrailerIdx(currentTrailerIdx - 1);
	};

	const scrollLeft = () => {
		if (sliderRef.current) sliderRef.current.scrollBy({ left: -sliderRef.current.offsetWidth, behavior: "smooth" });
	};
	const scrollRight = () => {
		if (sliderRef.current) sliderRef.current.scrollBy({ left: sliderRef.current.offsetWidth, behavior: "smooth" });
	};

	if (loading)
		return (
			<div className='min-h-screen bg-black p-10'>
				<WatchPageSkeleton />
			</div>
		);

	if (!content) {
		return (
			<div className='bg-black text-white h-screen'>
				<div className='max-w-6xl mx-auto'>
					<Navbar />
					<div className='text-center mx-auto px-4 py-8 h-full mt-40'>
						<h2 className='text-2xl sm:text-5xl font-bold text-balance'>Content not found 😥</h2>
					</div>
				</div>
			</div>
		);
	}

	return (
		<div className='bg-black min-h-screen text-white'>
			<div className='mx-auto container px-4 py-8 h-full'>
				<Navbar />

				{trailers.length > 0 && (
					<div className='flex justify-between items-center mb-4'>
						<button
							className={`
							bg-gray-500/70 hover:bg-gray-500 text-white py-2 px-4 rounded ${
								currentTrailerIdx === 0 ? "opacity-50 cursor-not-allowed " : ""
							}}
							`}
							disabled={currentTrailerIdx === 0}
							onClick={handlePrev}
						>
							<ChevronLeft size={24} />
						</button>

						<button
							className={`
							bg-gray-500/70 hover:bg-gray-500 text-white py-2 px-4 rounded ${
								currentTrailerIdx === trailers.length - 1 ? "opacity-50 cursor-not-allowed " : ""
							}}
							`}
							disabled={currentTrailerIdx === trailers.length - 1}
							onClick={handleNext}
						>
							<ChevronRight size={24} />
						</button>
					</div>
				)}

				<div className='aspect-video mb-8 p-2 sm:px-10 md:px-32'>
					{trailers.length > 0 && (
						<ReactPlayer
							controls={true}
							width={"100%"}
							height={"70vh"}
							className='mx-auto overflow-hidden rounded-lg'
							url={`https://www.youtube.com/watch?v=${trailers[currentTrailerIdx].key}`}
						/>
					)}

					{trailers?.length === 0 && (
						<h2 className='text-xl text-center mt-5'>
							No trailers available for{" "}
							<span className='font-bold text-red-600'>{content?.title || content?.name}</span> 😥
						</h2>
					)}
				</div>

				{/* movie details */}
				<div
					className='flex flex-col md:flex-row items-center justify-between gap-20 
				max-w-6xl mx-auto'
				>
					<div className='mb-4 md:mb-0'>
						<h2 className='text-5xl font-bold text-balance'>{content?.title || content?.name}</h2>

						<p className='mt-2 text-lg'>
							{formatReleaseDate(content?.release_date || content?.first_air_date)} |{" "}
							{content?.adult ? (
								<span className='text-red-600'>18+</span>
							) : (
								<span className='text-green-600'>PG-13</span>
							)}{" "}
						</p>
						<p className='mt-4 text-lg'>{content?.overview}</p>
					</div>
					<img
						src={ORIGINAL_IMG_BASE_URL + content?.poster_path}
						alt='Poster image'
						className='max-h-[600px] rounded-md'
					/>
				</div>

				{similarContent.length > 0 && (
					<div className='mt-12 max-w-5xl mx-auto relative'>
						<h3 className='text-3xl font-bold mb-4'>Similar Movies/Tv Show</h3>

						<div className='flex overflow-x-scroll scrollbar-hide gap-4 pb-4 group' ref={sliderRef}>
							{similarContent.map((content) => {
								if (content.poster_path === null) return null;
								return (
									<Link key={content.id} to={`/watch/${content.id}`} className='w-52 flex-none'>
										<img
											src={SMALL_IMG_BASE_URL + content.poster_path}
											alt='Poster path'
											className='w-full h-auto rounded-md'
										/>
										<h4 className='mt-2 text-lg font-semibold'>{content.title || content.name}</h4>
									</Link>
								);
							})}

							<ChevronRight
								className='absolute top-1/2 -translate-y-1/2 right-2 w-8 h-8
										opacity-0 group-hover:opacity-100 transition-all duration-300 cursor-pointer
										 bg-red-600 text-white rounded-full'
								onClick={scrollRight}
							/>
							<ChevronLeft
								className='absolute top-1/2 -translate-y-1/2 left-2 w-8 h-8 opacity-0 
								group-hover:opacity-100 transition-all duration-300 cursor-pointer bg-red-600 
								text-white rounded-full'
								onClick={scrollLeft}
							/>
						</div>
					</div>
				)}
			</div>
		</div>
	);
};
export default WatchPage;
