// frontend/src/pages/SearchPage.jsx
import { useState } from "react";
import { useContentStore } from "../store/content";
import Navbar from "../components/Navbar";
import { Search } from "lucide-react";
import toast from "react-hot-toast";
import axiosInstance from "/frontend/axiosConfig";
import { ORIGINAL_IMG_BASE_URL } from "../utils/constants";
import { Link } from "react-router-dom";

const SearchPage = () => {
	const [activeTab, setActiveTab] = useState("movie");
	const [searchTerm, setSearchTerm] = useState("");

	const [results, setResults] = useState([]);
	const { setContentType } = useContentStore();

	const handleTabClick = (tab) => {
		setActiveTab(tab);
		tab === "movie" ? setContentType("movie") : setContentType("tv");
		setResults([]);
	};

	const handleSearch = async (e) => {
		e.preventDefault();
		try {
			const res = await axiosInstance.get(`/api/v1/search/${activeTab}/${searchTerm}`);
			setResults(res.data.content);
		} catch (error) {
			if (error.response.status === 404) {
				toast.error("Nothing found, make sure you are searching under the right category");
			} else {
				toast.error("An error occurred, please try again later");
			}
		}
	};

	return (
		<div className='bg-black min-h-screen text-white'>
			<Navbar />
			<div className='container mx-auto px-4 py-8'>
				<div className='flex justify-center gap-3 mb-4'>
					<button
						className={`py-2 px-4 rounded ${
							activeTab === "movie" ? "bg-red-600" : "bg-gray-800"
						} hover:bg-red-700`}
						onClick={() => handleTabClick("movie")}
					>
						Movies
					</button>
					<button
						className={`py-2 px-4 rounded ${
							activeTab === "tv" ? "bg-red-600" : "bg-gray-800"
						} hover:bg-red-700`}
						onClick={() => handleTabClick("tv")}
					>
						TV Shows
					</button>
					<button
						className={`py-2 px-4 rounded ${
							activeTab === "person" ? "bg-red-600" : "bg-gray-800"
						} hover:bg-red-700`}
						onClick={() => handleTabClick("person")}
					>
						Person
					</button>
				</div>

				<form className='flex gap-2 items-stretch mb-8 max-w-2xl mx-auto' onSubmit={handleSearch}>
					<input
						type='text'
						value={searchTerm}
						onChange={(e) => setSearchTerm(e.target.value)}
						placeholder={"Search for a " + activeTab}
						className='w-full p-2 rounded bg-gray-800 text-white'
					/>
					<button className='bg-red-600 hover:bg-red-700 text-white p-2 rounded'>
						<Search className='size-6' />
					</button>
				</form>

				<div className='grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4'>
					{results.map((result) => {
						if (!result.poster_path && !result.profile_path) return null;

						return (
							<div key={result.id} className='bg-gray-800 p-4 rounded'>
								{activeTab === "person" ? (
									<div className='flex flex-col items-center'>
										<img
											src={ORIGINAL_IMG_BASE_URL + result.profile_path}
											alt={result.name}
											className='max-h-96 rounded mx-auto'
										/>
										<h2 className='mt-2 text-xl font-bold'>{result.name}</h2>
									</div>
								) : (
									<Link
										to={"/watch/" + result.id}
										onClick={() => {
											setContentType(activeTab);
										}}
									>
										<img
											src={ORIGINAL_IMG_BASE_URL + result.poster_path}
											alt={result.title || result.name}
											className='w-full h-auto rounded'
										/>
										<h2 className='mt-2 text-xl font-bold'>{result.title || result.name}</h2>
									</Link>
								)}
							</div>
						);
					})}
				</div>
			</div>
		</div>
	);
};
export default SearchPage;

// frontend/src/app/pages/search-page/search-page.component.ts
import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';
import { ToastrService } from 'ngx-toastr';
import { NavbarComponent } from '../../components/navbar/navbar.component';
import { ContentService } from '../../services/content.service';
import { LucideAngularModule, Search } from 'lucide-angular';
import { ORIGINAL_IMG_BASE_URL } from '../../constants';

@Component({
    selector: 'app-search-page',
    standalone: true,
    imports: [CommonModule, FormsModule, RouterLink, NavbarComponent, LucideAngularModule],
    templateUrl: './search-page.component.html'
})
export class SearchPageComponent {
    activeTab = signal<'movie' | 'tv' | 'person'>('movie');
    searchTerm = signal('');
    results = signal<any[]>([]);

    contentService = inject(ContentService);
    http = inject(HttpClient);
    toastr = inject(ToastrService);

    ORIGINAL_IMG_BASE_URL = ORIGINAL_IMG_BASE_URL;

    handleTabClick(tab: 'movie' | 'tv' | 'person') {
        this.activeTab.set(tab);
        if (tab === 'movie' || tab === 'tv') {
            this.contentService.setContentType(tab);
        }
        this.results.set([]);
    }

    handleSearch(event: Event) {
        event.preventDefault();
        this.http.get<{ content: any[] }>(`/api/v1/search/${this.activeTab()}/${this.searchTerm()}`)
            .subscribe({
                next: (res) => {
                    this.results.set(res.content);
                },
                error: (error: HttpErrorResponse) => {
                    if (error.status === 404) {
                        this.toastr.error('Nothing found, make sure you are searching under the right category');
                    } else {
                        this.toastr.error('An error occurred, please try again later');
                    }
                }
            });
    }
}

<div class="bg-black min-h-screen text-white">
    <app-navbar></app-navbar>
    <div class="container mx-auto px-4 py-8">
        <div class="flex justify-center gap-3 mb-4">
            <button class="py-2 px-4 rounded hover:bg-red-700" [class.bg-red-600]="activeTab() === 'movie'"
                [class.bg-gray-800]="activeTab() !== 'movie'" (click)="handleTabClick('movie')">
                Movies
            </button>
            <button class="py-2 px-4 rounded hover:bg-red-700" [class.bg-red-600]="activeTab() === 'tv'"
                [class.bg-gray-800]="activeTab() !== 'tv'" (click)="handleTabClick('tv')">
                TV Shows
            </button>
            <button class="py-2 px-4 rounded hover:bg-red-700" [class.bg-red-600]="activeTab() === 'person'"
                [class.bg-gray-800]="activeTab() !== 'person'" (click)="handleTabClick('person')">
                Person
            </button>
        </div>

        <form class="flex gap-2 items-stretch mb-8 max-w-2xl mx-auto" (submit)="handleSearch($event)">
            <input type="text" [ngModel]="searchTerm()" (ngModelChange)="searchTerm.set($event)" name="search"
                placeholder="Search for a {{ activeTab() }}" class="w-full p-2 rounded bg-gray-800 text-white" />
            <button class="bg-red-600 hover:bg-red-700 text-white p-2 rounded">
                <lucide-icon name="search" class="size-6"></lucide-icon>
            </button>
        </form>

        <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            @for (result of results(); track result.id) {
            @if (result.poster_path || result.profile_path) {
            <div class="bg-gray-800 p-4 rounded">
                @if (activeTab() === 'person') {
                <div class="flex flex-col items-center">
                    <img [src]="ORIGINAL_IMG_BASE_URL + result.profile_path" [alt]="result.name"
                        class="max-h-96 rounded mx-auto" />
                    <h2 class="mt-2 text-xl font-bold">{{ result.name }}</h2>
                </div>
                } @else {
                <a [routerLink]="['/watch', result.id]"
                    (click)="contentService.setContentType(activeTab() === 'movie' ? 'movie' : 'tv')">
                    <img [src]="ORIGINAL_IMG_BASE_URL + result.poster_path" [alt]="result.title || result.name"
                        class="w-full h-auto rounded" />
                    <h2 class="mt-2 text-xl font-bold">{{ result.title || result.name }}</h2>
                </a>
                }
            </div>
            }
            }
        </div>
    </div>
</div>
